/**
 * Typed test fixtures for Tushare module.
 *
 * Loads raw JSON responses from fixtures/raw/ (generated by
 * scripts/generate-tushare-fixtures.ts) and re-exports them with proper
 * TypeScript types so tests can import realistic API data without hitting
 * the network.
 *
 * If the raw files don't exist yet (i.e. the generation script hasn't been
 * run), each fixture falls back to a minimal inline stub so unit tests can
 * still run in CI without a TUSHARE_API_KEY.
 */

import type { TushareRawResponse } from '../types/api.js';

// ── Loader helper ─────────────────────────────────────────────────────────────

function loadRaw(filename: string, fallback: TushareRawResponse): TushareRawResponse {
  try {
    // Dynamic require works in Bun for JSON files
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    return require(`./fixtures/raw/${filename}`) as TushareRawResponse;
  } catch {
    return fallback;
  }
}

// ── Minimal stubs (used when raw files are absent) ────────────────────────────

function makeStub(fields: string[], rows: Array<Array<string | number | null>>): TushareRawResponse {
  return {
    request_id: 'stub',
    code: 0,
    msg: null,
    data: { fields, items: rows },
  };
}

// ── Price fixtures ────────────────────────────────────────────────────────────

export const dailyFixture: TushareRawResponse = loadRaw(
  'daily.json',
  makeStub(
    ['ts_code', 'trade_date', 'open', 'high', 'low', 'close', 'pre_close', 'change', 'pct_chg', 'vol', 'amount'],
    [['600519.SH', '20240115', 1700.0, 1720.0, 1695.0, 1710.0, 1698.0, 12.0, 0.71, 12345.6, 21098765.0]]
  )
);

export const dailyBasicFixture: TushareRawResponse = loadRaw(
  'daily_basic.json',
  makeStub(
    ['ts_code', 'trade_date', 'close', 'turnover_rate', 'turnover_rate_f', 'volume_ratio', 'pe', 'pe_ttm', 'pb', 'ps', 'ps_ttm', 'dv_ratio', 'dv_ttm', 'total_share', 'float_share', 'total_mv', 'circ_mv'],
    [['600519.SH', '20240115', 1710.0, 0.21, 0.35, 1.02, 28.5, 27.9, 10.2, 8.5, 8.3, 1.8, 1.7, 125620.0, 98450.0, 214809220.0, 168349500.0]]
  )
);

// ── Fundamental fixtures ──────────────────────────────────────────────────────

export const incomeFixture: TushareRawResponse = loadRaw(
  'income.json',
  makeStub(
    ['ts_code', 'ann_date', 'f_ann_date', 'end_date', 'report_type', 'total_revenue', 'revenue', 'total_cogs', 'oper_cost', 'sell_exp', 'admin_exp', 'rd_exp', 'fin_exp', 'operate_profit', 'total_profit', 'income_tax', 'n_income', 'n_income_attr_p', 'basic_eps', 'diluted_eps'],
    [['600519.SH', '20240330', '20240330', '20231231', '1', 150000000000.0, 149000000000.0, 20000000000.0, 15000000000.0, 2000000000.0, 3000000000.0, 500000000.0, 100000000.0, 80000000000.0, 82000000000.0, 12000000000.0, 70000000000.0, 69000000000.0, 54.9, 54.8]]
  )
);

export const balancesheetFixture: TushareRawResponse = loadRaw(
  'balancesheet.json',
  makeStub(
    ['ts_code', 'ann_date', 'f_ann_date', 'end_date', 'report_type', 'total_assets', 'total_liab', 'total_hldr_eqy_exc_min_int', 'total_cur_assets', 'total_nca', 'total_cur_liab', 'total_ncl', 'money_cap', 'accounts_receiv', 'inventories', 'fix_assets', 'intan_assets', 'goodwill', 'lt_borr', 'bond_payable'],
    [['600519.SH', '20240330', '20240330', '20231231', '1', 300000000000.0, 80000000000.0, 220000000000.0, 180000000000.0, 120000000000.0, 60000000000.0, 20000000000.0, 50000000000.0, 1000000000.0, 40000000000.0, 5000000000.0, 2000000000.0, 0.0, 0.0, 0.0]]
  )
);

export const cashflowFixture: TushareRawResponse = loadRaw(
  'cashflow.json',
  makeStub(
    ['ts_code', 'ann_date', 'f_ann_date', 'end_date', 'report_type', 'n_cashflow_act', 'n_cashflow_inv_act', 'n_cash_flows_fnc_act', 'c_fr_sale_sg', 'c_paid_goods_s', 'c_paid_to_for_empl', 'c_paid_for_taxes', 'n_incr_cash_cash_equ', 'c_cash_equ_beg_period', 'c_cash_equ_end_period', 'free_cashflow'],
    [['600519.SH', '20240330', '20240330', '20231231', '1', 75000000000.0, -10000000000.0, -30000000000.0, 150000000000.0, 15000000000.0, 5000000000.0, 20000000000.0, 35000000000.0, 15000000000.0, 50000000000.0, 65000000000.0]]
  )
);

export const finaIndicatorFixture: TushareRawResponse = loadRaw(
  'fina_indicator.json',
  makeStub(
    ['ts_code', 'ann_date', 'end_date', 'eps', 'bps', 'roe', 'roe_dt', 'roa', 'grossprofit_margin', 'netprofit_margin', 'debt_to_assets', 'current_ratio', 'quick_ratio', 'ocf_to_or', 'ocf_to_opincome', 'inc_revenue_yoy', 'inc_net_profit_yoy', 'inc_total_assets_yoy'],
    [['600519.SH', '20240330', '20231231', 54.9, 174.8, 31.4, 30.1, 23.0, 91.5, 46.3, 26.7, 3.0, 2.8, 0.50, 0.94, 18.0, 19.2, 12.5]]
  )
);

// ── Market data fixtures ──────────────────────────────────────────────────────

export const moneyflowHsgtFixture: TushareRawResponse = loadRaw(
  'moneyflow_hsgt.json',
  makeStub(
    ['trade_date', 'ggt_ss', 'ggt_sz', 'hgt', 'sgt', 'north_money', 'south_money'],
    [
      ['20240115', 1200000000.0, 800000000.0, 1500000000.0, 900000000.0, 4400000000.0, 2100000000.0],
      ['20240112', -500000000.0, -300000000.0, -600000000.0, -400000000.0, -1800000000.0, 1000000000.0],
    ]
  )
);

export const marginFixture: TushareRawResponse = loadRaw(
  'margin.json',
  makeStub(
    ['trade_date', 'ts_code', 'rzye', 'rqye', 'rzmre', 'rqmcl', 'rzche', 'rqchl'],
    [['20240115', '600519.SH', 500000000.0, 10000000.0, 50000000.0, 1000000.0, 45000000.0, 900000.0]]
  )
);

export const blockTradeFixture: TushareRawResponse = loadRaw(
  'block_trade.json',
  makeStub(
    ['ts_code', 'trade_date', 'price', 'vol', 'amount', 'buyer', 'seller'],
    [['600519.SH', '20240115', 1705.0, 50000.0, 85250000.0, '机构专用', '机构专用']]
  )
);

export const limitListFixture: TushareRawResponse = loadRaw(
  'limit_list.json',
  makeStub(
    ['trade_date', 'ts_code', 'name', 'close', 'pct_chg', 'amount', 'limit_type', 'times'],
    [
      ['20240115', '000001.SZ', '平安银行', 10.5, 10.0, 1234567890.0, 'U', 1],
      ['20240115', '000002.SZ', '万科A', 8.2, -10.0, 987654321.0, 'D', 1],
    ]
  )
);

// ── Weekly/Monthly adjusted price fixtures ────────────────────────────────────

export const stkWeekMonthAdjFixture: TushareRawResponse = loadRaw(
  'stk_week_month_adj.json',
  makeStub(
    [
      'ts_code', 'trade_date', 'freq',
      'open', 'high', 'low', 'close', 'pre_close',
      'open_qfq', 'high_qfq', 'low_qfq', 'close_qfq',
      'open_hfq', 'high_hfq', 'low_hfq', 'close_hfq',
      'vol', 'amount', 'change', 'pct_chg',
    ],
    [
      ['000001.SZ', '20250117', 'week', 11.25, 11.59, 11.08, 11.45, 11.30,
        11.25, 11.59, 11.08, 11.45, 1437.57, 1481.02, 1415.85, 1463.13,
        4353954.80, 4963695.53, 0.15, 0.01],
      ['000001.SZ', '20250110', 'week', 11.38, 11.63, 11.22, 11.30, 11.38,
        11.38, 11.63, 11.22, 11.30, 1454.18, 1486.13, 1433.74, 1443.96,
        4445402.00, 5079074.95, -0.08, -0.01],
    ]
  )
);

// ── Reference data fixtures ───────────────────────────────────────────────────

export const stockBasicFixture: TushareRawResponse = loadRaw(
  'stock_basic.json',
  makeStub(
    ['ts_code', 'symbol', 'name', 'area', 'industry', 'market', 'list_date', 'exchange', 'curr_type', 'list_status'],
    [
      ['600519.SH', '600519', '贵州茅台', '贵州', '白酒', '主板', '20010827', 'SSE', 'CNY', 'L'],
      ['601398.SH', '601398', '工商银行', '北京', '银行', '主板', '20061027', 'SSE', 'CNY', 'L'],
    ]
  )
);

export const tradeCalFixture: TushareRawResponse = loadRaw(
  'trade_cal.json',
  makeStub(
    ['exchange', 'cal_date', 'is_open', 'pretrade_date'],
    [
      ['SSE', '20240115', 1, '20240112'],
      ['SSE', '20240114', 0, '20240112'],
      ['SSE', '20240113', 0, '20240112'],
      ['SSE', '20240112', 1, '20240111'],
    ]
  )
);
